import Lambert.Arithmetic.NumberFieldHeightExtension

/-! # Height bounds for fields generated by positive radicals -/
namespace Lambert
noncomputable section
open Polynomial IntermediateField

/-- A real radical greater than one has unnormalized height equal to its generated-field degree times its logarithm. -/
theorem radical_generatedField_height_eq
    (q : ℝ) (hq : 1 < q) (n m : ℕ) (hn : 0 < n) (hpow : q^n=m)
    [NumberField ℚ⟮q⟯] :
    Height.logHeight₁ (AdjoinSimple.gen ℚ q) =
      (Module.finrank ℚ ℚ⟮q⟯ : ℝ)*Real.log q := by
  let qK : ℚ⟮q⟯ := AdjoinSimple.gen ℚ q
  have hm : 0 < m := by
    have hp := pow_pos (zero_lt_one.trans hq) n
    rw [hpow] at hp
    exact_mod_cast hp
  have hpowK : qK^n = (m : ℚ⟮q⟯) := by
    apply (ℚ⟮q⟯).subtype.injective
    rw [map_pow, map_natCast]
    exact hpow
  let : NeZero m := ⟨hm.ne'⟩
  have hH := numberField_logHeight_extension
    (L := ℚ⟮q⟯) (m : ℚ)
  simp only [map_natCast, Rat.logHeight₁_natCast] at hH
  rw [← hpowK, Height.logHeight₁_pow] at hH
  have hlog : Real.log (m : ℝ) = (n : ℝ)*Real.log q := by rw [← hpow, Real.log_pow]
  rw [hlog] at hH
  apply mul_left_cancel₀ (show (n : ℝ) ≠ 0 by exact_mod_cast hn.ne')
  nlinarith [hH]

/-- The field generated by a root of X^n-m has degree at most n when n is positive. -/
theorem radical_generatedField_finrank_le
    (q : ℝ) (n m : ℕ) (hn : 0 < n) (hpow : q^n=m) :
    Module.finrank ℚ ℚ⟮q⟯ ≤ n := by
  have hroot : aeval q (X^n-C (m : ℚ))=0 := by simp [hpow]
  have hqi : IsIntegral ℚ q := ⟨X^n-C (m : ℚ), monic_X_pow_sub_C _ hn.ne', hroot⟩
  rw [adjoin.finrank hqi]
  have he := natDegree_le_of_dvd (minpoly.dvd ℚ q hroot) (monic_X_pow_sub_C (m : ℚ) hn.ne').ne_zero
  simpa only [natDegree_X_pow_sub_C] using he

end
end Lambert
