import Lambert.Arithmetic.NodalFunctional
import Lambert.Arithmetic.GeometricMoments
import Mathlib.FieldTheory.RatFunc.AsPolynomial

/-!
# Polynomial Lambert functionals and finite-window data

The input polynomial variable represents the integration variable. The output
polynomial variable represents the unknown Lambert value. Taking the coefficient
field to be `RatFunc ℚ` keeps the base itself indeterminate.
-/

namespace Lambert

open Polynomial Finset

noncomputable section

variable {K : Type*} [Field K]

/-- The polynomial Lambert functional sends the monomial of degree `r` to
the reciprocal of `q^(r+1)-1`. -/
def lambertPolynomialFunctional (q : K) : K[X] →ₗ[K] K[X] :=
  Polynomial.lsum fun r =>
    LinearMap.toSpanSingleton K K[X] (C (1 / (q ^ (r + 1) - 1)))

/-- Every polynomial monomial has its specified reciprocal-geometric moment. -/
theorem lambertPolynomialFunctional_X_pow (q : K) (r : ℕ) :
    lambertPolynomialFunctional q (X ^ r) = C (1 / (q ^ (r + 1) - 1)) := by
  simp [lambertPolynomialFunctional, Polynomial.lsum, ← monomial_one_right_eq_X_pow,
    Polynomial.sum_monomial_index, LinearMap.toSpanSingleton_apply]

/-- The simple-pole Lambert entry is generated by multiplication by its pole
and subtraction of the next polynomial moment. -/
def lambertPoleEntry (q : K) : ℕ → ℕ → K[X]
  | 0, j => X - C (geometricMomentPrefix q j)
  | i + 1, j => C (q ^ j) * lambertPoleEntry q i j - C (1 / (q ^ (i + 1) - 1))

/-- The zeroth simple-pole entry is the unknown value minus its finite prefix. -/
@[simp] theorem lambertPoleEntry_zero (q : K) (j : ℕ) :
    lambertPoleEntry q 0 j = X - C (geometricMomentPrefix q j) := rfl

/-- Increasing the moment index gives the exact simple-pole recurrence. -/
theorem lambertPoleEntry_succ (q : K) (i j : ℕ) :
    lambertPoleEntry q (i + 1) j =
      C (q ^ j) * lambertPoleEntry q i j - C (1 / (q ^ (i + 1) - 1)) := rfl

/-- Lambert entries commute with field embeddings of the base and coefficients. -/
theorem lambertPoleEntry_map {F : Type*} [Field F] (f : K →+* F) (q : K) (i j : ℕ) :
    (lambertPoleEntry q i j).map f = lambertPoleEntry (f q) i j := by
  induction i with
  | zero =>
    rw [lambertPoleEntry_zero, Polynomial.map_sub, Polynomial.map_X, Polynomial.map_C,
      lambertPoleEntry_zero]
    simp [geometricMomentPrefix]
  | succ i ih =>
    rw [lambertPoleEntry_succ, Polynomial.map_sub, Polynomial.map_mul, Polynomial.map_C, ih,
      Polynomial.map_C, lambertPoleEntry_succ]
    simp

/-- At bases with no positive power equal to one, the simple-pole entries
satisfy the same recurrence in their second index. -/
theorem lambertPoleEntry_succ_right (q : K)
    (hq : ∀ n : ℕ, q ^ (n + 1) ≠ 1) (i j : ℕ) :
    lambertPoleEntry q i (j + 1) =
      C (q ^ i) * lambertPoleEntry q i j - C (1 / (q ^ (j + 1) - 1)) := by
  induction i with
  | zero => simp [lambertPoleEntry, geometricMomentPrefix, sum_range_succ, map_add]; ring
  | succ i ih =>
    rw [lambertPoleEntry_succ, ih, lambertPoleEntry_succ]
    have hi : (C (q ^ (i + 1)) - 1) * C (1 / (q ^ (i + 1) - 1)) = (1 : K[X]) := by
      rw [← C_1, ← map_sub, ← map_mul]
      simp [sub_ne_zero.mpr (hq i)]
    have hj : (C (q ^ (j + 1)) - 1) * C (1 / (q ^ (j + 1) - 1)) = (1 : K[X]) := by
      rw [← C_1, ← map_sub, ← map_mul]
      simp [sub_ne_zero.mpr (hq j)]
    simp only [pow_succ, map_mul] at *
    linear_combination hi - hj

/-- At bases with no positive power equal to one, the simple-pole Lambert
matrix is symmetric at every pair of indices. -/
theorem lambertPoleEntry_symm (q : K)
    (hq : ∀ n : ℕ, q ^ (n + 1) ≠ 1) (i j : ℕ) :
    lambertPoleEntry q i j = lambertPoleEntry q j i := by
  induction i generalizing j with
  | zero =>
    induction j with
    | zero => rfl
    | succ j ih =>
      rw [lambertPoleEntry_succ_right q hq, ih, lambertPoleEntry_succ]
  | succ i ih =>
    rw [lambertPoleEntry_succ, ih, lambertPoleEntry_succ_right q hq]

/-- The polynomial Lambert functional always has constant output. -/
theorem lambertPolynomialFunctional_eq_C (q : K) (p : K[X]) :
    lambertPolynomialFunctional q p =
      C (p.sum fun r a => a * (1 / (q ^ (r + 1) - 1))) := by
  simp [lambertPolynomialFunctional, Polynomial.lsum, Polynomial.sum,
    LinearMap.toSpanSingleton_apply, smul_eq_C_mul, map_sum, map_mul]

/-- Powers of the rational-function indeterminate are pairwise distinct. -/
theorem ratFunc_X_pow_injective : Function.Injective (fun n : ℕ => (RatFunc.X : RatFunc ℚ) ^ n) := by
  intro i j hij
  have he : algebraMap ℚ[X] (RatFunc ℚ) ((X : ℚ[X]) ^ i) =
      algebraMap ℚ[X] (RatFunc ℚ) ((X : ℚ[X]) ^ j) := by
    simpa only [map_pow, RatFunc.algebraMap_X] using hij
  have hp := (IsFractionRing.injective ℚ[X] (RatFunc ℚ)) he
  simpa only [natDegree_X_pow] using congrArg Polynomial.natDegree hp

/-- Every positive power difference in the formal Lambert base is nonzero. -/
theorem ratFunc_X_pow_sub_one_ne_zero (n : ℕ) :
    (RatFunc.X : RatFunc ℚ) ^ (n + 1) - 1 ≠ 0 := by
  apply sub_ne_zero.mpr
  intro he
  have hn := ratFunc_X_pow_injective (he.trans (pow_zero _).symm)
  omega

section Map
variable {F : Type*} [Field F]
private theorem polynomialFunctional_monomial (q : K) (r : ℕ) (a : K) :
    lambertPolynomialFunctional q (monomial r a) = C a * C (1 / (q ^ (r + 1) - 1)) := by
  rw [← smul_X_eq_monomial, map_smul, lambertPolynomialFunctional_X_pow, smul_eq_C_mul]

/-- The polynomial Lambert functional commutes with coefficient embeddings. -/
theorem lambertPolynomialFunctional_map (f : K →+* F) (q : K) (p : K[X]) :
    (lambertPolynomialFunctional q p).map f = lambertPolynomialFunctional (f q) (p.map f) := by
  induction p using Polynomial.induction_on' with
  | add p r hp hr => simp only [map_add, Polynomial.map_add, hp, hr]
  | monomial r a =>
    rw [Polynomial.map_monomial, polynomialFunctional_monomial, polynomialFunctional_monomial]
    simp

end Map

end
end Lambert
